12:14:18 AM: DEBUG [logger_base.py:16] mensaje a nivel debug
12:14:18 AM: INFO [logger_base.py:17] mensaje a nivel info
12:14:18 AM: WARNING [logger_base.py:18] mensaje a nivel warning
12:14:18 AM: ERROR [logger_base.py:19] mensaje a nivel error
12:14:18 AM: CRITICAL [logger_base.py:20] mensaje a nivel critical
12:14:18 AM: DEBUG [logger_base.py:21] se realizó la conexión con exito
11:12:24 AM: DEBUG [conexion.py:23] Conexión exitosa: <connection object at 0x0324E910; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
11:12:24 AM: DEBUG [conexion.py:36] Se abrio el cursor con éxito: <cursor object at 0x0324C828; closed: 0>
11:12:24 AM: DEBUG [persona_dao.py:67] b'DELETE FROM persona WHERE id_persona = %s'
11:12:24 AM: DEBUG [persona_dao.py:68] Persona a eliminar: Id Persona: 7, Nombre: None, Apellido: None, Email: None
11:12:24 AM: DEBUG [conexion.py:56] Se han cerrado los objetos de conexión y cursor
11:12:24 AM: DEBUG [persona_dao.py:98] Personas eliminadas: 0
11:15:26 AM: DEBUG [conexion.py:23] Conexión exitosa: <connection object at 0x02EC2748; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
11:15:26 AM: DEBUG [conexion.py:36] Se abrio el cursor con éxito: <cursor object at 0x02E7F828; closed: 0>
11:15:26 AM: DEBUG [persona_dao.py:18] b'SELECT * FROM persona ORDER BY id_persona'
11:15:26 AM: DEBUG [conexion.py:56] Se han cerrado los objetos de conexión y cursor
11:15:26 AM: DEBUG [persona_dao.py:82] Id Persona: 1, Nombre: juan, Apellido: cordoneda, Email: ñandu
11:15:26 AM: DEBUG [persona_dao.py:83] 1
11:15:26 AM: DEBUG [persona_dao.py:82] Id Persona: 2, Nombre: juan ignacio, Apellido: capocceti, Email: juani

11:15:26 AM: DEBUG [persona_dao.py:83] 2
11:15:26 AM: DEBUG [persona_dao.py:82] Id Persona: 3, Nombre: justo, Apellido: gonzalez, Email: tito

11:15:26 AM: DEBUG [persona_dao.py:83] 3
11:15:26 AM: DEBUG [persona_dao.py:82] Id Persona: 4, Nombre: patricio, Apellido: cancillieri, Email: pato
11:15:26 AM: DEBUG [persona_dao.py:83] 4
11:15:26 AM: DEBUG [persona_dao.py:82] Id Persona: 5, Nombre: camilo, Apellido: nahmiyas, Email: jurio
11:15:26 AM: DEBUG [persona_dao.py:83] 5
11:15:26 AM: DEBUG [persona_dao.py:82] Id Persona: 9, Nombre: Marcos, Apellido: Gonzalez, Email: gordo
11:15:26 AM: DEBUG [persona_dao.py:83] 9
11:35:35 AM: DEBUG [conexion.py:23] Conexión exitosa: <connection object at 0x0304F9A8; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
11:35:35 AM: DEBUG [conexion.py:36] Se abrio el cursor con éxito: <cursor object at 0x0304C8A8; closed: 0>
11:35:35 AM: INFO [conexion.py:59] <cursor object at 0x0304C8A8; closed: 0>
11:35:35 AM: DEBUG [conexion.py:56] Se han cerrado los objetos de conexión y cursor
11:35:48 AM: DEBUG [conexion.py:23] Conexión exitosa: <connection object at 0x03963748; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
11:35:48 AM: DEBUG [conexion.py:36] Se abrio el cursor con éxito: <cursor object at 0x039607A8; closed: 0>
11:35:48 AM: INFO [conexion.py:59] <cursor object at 0x039607A8; closed: 0>
11:35:53 AM: DEBUG [conexion.py:23] Conexión exitosa: <connection object at 0x035A3748; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
11:35:53 AM: DEBUG [conexion.py:36] Se abrio el cursor con éxito: <cursor object at 0x035A07A8; closed: 0>
11:35:53 AM: INFO [conexion.py:59] <cursor object at 0x035A07A8; closed: 0>
11:35:53 AM: DEBUG [conexion.py:56] Se han cerrado los objetos de conexión y cursor
11:36:37 AM: DEBUG [conexion.py:23] Conexión exitosa: <connection object at 0x02FC3748; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
11:36:37 AM: DEBUG [conexion.py:36] Se abrio el cursor con éxito: <cursor object at 0x02FC07A8; closed: 0>
11:36:37 AM: INFO [conexion.py:59] <cursor object at 0x02FC07A8; closed: 0>
11:36:37 AM: DEBUG [conexion.py:56] Se han cerrado los objetos de conexión y cursor
11:36:56 AM: DEBUG [conexion.py:23] Conexión exitosa: <connection object at 0x03A83748; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
11:36:56 AM: DEBUG [conexion.py:36] Se abrio el cursor con éxito: <cursor object at 0x03A807A8; closed: 0>
11:36:56 AM: INFO [conexion.py:59] <cursor object at 0x03A807A8; closed: 0>
11:36:56 AM: INFO [conexion.py:60] <connection object at 0x03A83748; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
11:36:56 AM: DEBUG [conexion.py:56] Se han cerrado los objetos de conexión y cursor
11:45:35 AM: DEBUG [persona.py:45] Id Persona: 1, Nombre: Juan, Apellido: Perez, Email: email
11:45:35 AM: DEBUG [persona.py:49] Id Persona: None, Nombre: Karla, Apellido: Gomez, Email: kgomez@mail.com
11:45:35 AM: DEBUG [persona.py:52] Id Persona: 3, Nombre: None, Apellido: None, Email: None
11:49:26 AM: DEBUG [conexion.py:23] Conexión exitosa: <connection object at 0x03B309A8; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
11:49:26 AM: DEBUG [conexion.py:36] Se abrio el cursor con éxito: <cursor object at 0x03B2C928; closed: 0>
11:49:26 AM: DEBUG [persona_dao.py:18] b'SELECT * FROM persona ORDER BY id_persona'
11:49:26 AM: DEBUG [conexion.py:56] Se han cerrado los objetos de conexión y cursor
11:49:26 AM: DEBUG [persona_dao.py:83] Id Persona: 1, Nombre: juan, Apellido: cordoneda, Email: ñandu
11:49:26 AM: DEBUG [persona_dao.py:84] 1
11:49:26 AM: DEBUG [persona_dao.py:83] Id Persona: 2, Nombre: juan ignacio, Apellido: capocceti, Email: juani

11:49:26 AM: DEBUG [persona_dao.py:84] 2
11:49:26 AM: DEBUG [persona_dao.py:83] Id Persona: 3, Nombre: justo, Apellido: gonzalez, Email: tito

11:49:26 AM: DEBUG [persona_dao.py:84] 3
11:49:26 AM: DEBUG [persona_dao.py:83] Id Persona: 4, Nombre: patricio, Apellido: cancillieri, Email: pato
11:49:26 AM: DEBUG [persona_dao.py:84] 4
11:49:26 AM: DEBUG [persona_dao.py:83] Id Persona: 5, Nombre: camilo, Apellido: nahmiyas, Email: jurio
11:49:26 AM: DEBUG [persona_dao.py:84] 5
11:49:26 AM: DEBUG [persona_dao.py:83] Id Persona: 9, Nombre: Marcos, Apellido: Gonzalez, Email: gordo
11:49:26 AM: DEBUG [persona_dao.py:84] 9
11:50:07 AM: DEBUG [conexion.py:23] Conexión exitosa: <connection object at 0x03582748; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
11:50:07 AM: DEBUG [conexion.py:36] Se abrio el cursor con éxito: <cursor object at 0x035807A8; closed: 0>
11:50:07 AM: DEBUG [persona_dao.py:18] b'SELECT * FROM persona ORDER BY id_persona'
11:50:07 AM: DEBUG [conexion.py:56] Se han cerrado los objetos de conexión y cursor
11:50:07 AM: DEBUG [persona_dao.py:83] Id Persona: 1, Nombre: juan, Apellido: cordoneda, Email: ñandu
11:50:07 AM: DEBUG [persona_dao.py:83] Id Persona: 2, Nombre: juan ignacio, Apellido: capocceti, Email: juani

11:50:07 AM: DEBUG [persona_dao.py:83] Id Persona: 3, Nombre: justo, Apellido: gonzalez, Email: tito

11:50:07 AM: DEBUG [persona_dao.py:83] Id Persona: 4, Nombre: patricio, Apellido: cancillieri, Email: pato
11:50:07 AM: DEBUG [persona_dao.py:83] Id Persona: 5, Nombre: camilo, Apellido: nahmiyas, Email: jurio
11:50:07 AM: DEBUG [persona_dao.py:83] Id Persona: 9, Nombre: Marcos, Apellido: Gonzalez, Email: gordo
11:51:26 AM: DEBUG [conexion.py:23] Conexión exitosa: <connection object at 0x03652748; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
11:51:26 AM: DEBUG [conexion.py:36] Se abrio el cursor con éxito: <cursor object at 0x036507A8; closed: 0>
11:51:26 AM: DEBUG [persona_dao.py:33] b'INSERT INTO persona(nombre, apellido, email) VALUES(%s,%s,%s)'
11:51:26 AM: DEBUG [persona_dao.py:34] Persona a insertar: Id Persona: None, Nombre: Pedro, Apellido: Najera, Email: pnajera@mail.com
11:51:26 AM: ERROR [persona_dao.py:41] Excepción al insertar persona:column "email" of relation "persona" does not exist
LINE 1: INSERT INTO persona(nombre, apellido, email) VALUES('Pedro',...
                                              ^

11:51:26 AM: DEBUG [conexion.py:56] Se han cerrado los objetos de conexión y cursor
11:51:26 AM: DEBUG [persona_dao.py:89] Personas insertados: None
11:52:51 AM: DEBUG [conexion.py:23] Conexión exitosa: <connection object at 0x032DE910; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
11:52:51 AM: DEBUG [conexion.py:36] Se abrio el cursor con éxito: <cursor object at 0x032DC828; closed: 0>
11:52:51 AM: DEBUG [persona_dao.py:33] b'INSERT INTO persona(nombre, apellido, apodo) VALUES(%s,%s,%s)'
11:52:51 AM: DEBUG [persona_dao.py:34] Persona a insertar: Id Persona: None, Nombre: Pedro, Apellido: Najera, apodo: pnajera@mail.com
11:52:51 AM: DEBUG [conexion.py:56] Se han cerrado los objetos de conexión y cursor
11:52:51 AM: DEBUG [persona_dao.py:89] Personas insertados: 1
11:54:34 AM: DEBUG [conexion.py:23] Conexión exitosa: <connection object at 0x03A52748; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
11:54:34 AM: DEBUG [conexion.py:36] Se abrio el cursor con éxito: <cursor object at 0x03A507A8; closed: 0>
11:54:34 AM: DEBUG [persona_dao.py:50] b'UPDATE persona SET nombre=%s, apellido=%s, apodo=%s WHERE id_persona=%s'
11:54:34 AM: DEBUG [persona_dao.py:51] Persona a actualizar: Id Persona: 13, Nombre: Juan, Apellido: Perez, apodo: perez
11:54:34 AM: DEBUG [conexion.py:56] Se han cerrado los objetos de conexión y cursor
11:54:34 AM: DEBUG [persona_dao.py:94] Personas actualizadas: 1
